# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Sirof's Page
email: bsirof@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The home for all of my work.  As time goes on, I will be filling
  this site with my original page designs, fun games, and updates about
  me and my work.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://bensirof.me" # the base hostname & protocol for your site
twitter_username: bsirof
github_username:  bensirof

# Build settings
markdown: kramdown
